name: Code Quality

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  lint-and-format:
    name: Check Code Formatting and Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install format/lint tools
        run: |
          pip install black flake8 isort

      - name: Check formatting with black
        run: |
          black . --check

      - name: Check import order with isort
        run: |
          isort . --check-only

      - name: Lint code with flake8
        run: |
          flake8 .
