name: Secret Scan

# ✅ Run this workflow on any push or pull request
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  secret-scan:
    name: Scan for Exposed Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install GitLeaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64 -o gitleaks
          chmod +x gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Run GitLeaks
        run: |
          gitleaks detect --source=. --verbose --redact --exit-code 1
